version: "3.9"

services:
  mysql:
    image: mysql:8.0.25
    container_name: tema3_mysql
    environment:
      MYSQL_DATABASE: error
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: application_user
      MYSQL_PASSWORD: secret
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - 3382:3306
    volumes:
      - tema3_mysql:/data/mysql

    networks:
      - tema3

  postgres:
    image: postgres:14.1-alpine
    container_name: tema3_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - tema3_postgres:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - tema3


volumes:
  tema3_mysql:
    driver: local
  tema3_postgres:
    driver: local

networks:
  tema3:
    driver: bridge